env:
  TERM: xterm-256color
window:
  startup_mode: Maximized
  padding:
    x: 5
    y: 0
  dynamic_padding: true
  decorations: none

colors:
  # Default colors
  primary:
    background: '0x1e1e1e'
    foreground: '0xa7a7a7'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1e1e1e'
    cursor: '0xa7a7a7'

  # Normal colors
  normal:
    black:   '0x1e1e1e'
    red:     '0xcf6a4c'
    green:   '0x8f9d6a'
    yellow:  '0xf9ee98'
    blue:    '0x7587a6'
    magenta: '0x9b859d'
    cyan:    '0xafc4db'
    white:   '0xa7a7a7'

  # Bright colors
  bright:
    black:   '0x5f5a60'
    red:     '0xcda869'
    green:   '0x323537'
    yellow:  '0x464b50'
    blue:    '0x838184'
    magenta: '0xc3c3c3'
    cyan:    '0x9b703f'
    white:   '0xffffff'

draw_bold_text_with_bright_colors: false

font:
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Regular
  size: 10.0

cursor:
  blinking: On

shell:
  program: /usr/bin/fish
  args:
    - -l
    - -c
    - "tmux"
